version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '4040-4045:4040-4045'  # Spark shell UI
      - '8080:8080'  # Spark master UI
      - '7077:7077'  # Spark master url
    volumes:
      - ./:/workspace
      - ./data:/data
      - ./conf/log4j.properties:/opt/bitnami/spark/conf/log4j.properties:ro
    networks:
      - bobafett-net

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./:/workspace
      - ./data:/data
    networks:
      - bobafett-net

networks:
  bobafett-net:
    driver: bridge
    name: bobafett-net